### ISSUE TITLE
issue with the use of "/" to search animes like Fate/Zero

### ISSUE THREAD

**Issue by mathieu-celerier** [LetrixZ/animethemes-api#1]
When using this endpoint "https://animethemes-api.herokuapp.com/api/v1/search/" to search for anime like the Fate series I need to give the tittle with a "/" in it.
But the api then don't find an end point because the "/" is interpreted as part of the url not part of the "variable".

Any idea to go arround, or could you fix this ?

Great Thanks to you for this amazing API, really good work

Mat

**Comment by LetrixZ** [comment]
It should work fine now.
