### ISSUE TITLE
"Anime not found" for Winter 2021 anime

### ISSUE THREAD

**Issue by SombraVerdad** [LetrixZ/animethemes-api#15]
I tried using APIs with two anime from the Winter 2021 season, but I got the error "Anime not found" : 

- Dr Stone : Stone Wars  -> 40852 -> https://animethemes-api.herokuapp.com/api/v1/anime/40852 
- That Time I Got Reincarnated as a Slime Season 2 -> 39551 -> https://animethemes-api.herokuapp.com/api/v1/anime/39551

It's weird, I did a search on r / AnimeThemes and I found the openings of these two anime : 
- https://www.reddit.com/r/AnimeThemes/comments/kx90la/dr_stone_stone_wars_winter_2021_op_rakuen_op720/
- https://www.reddit.com/r/AnimeThemes/comments/kvv7vt/tensei_shitara_slime_datta_ken_2nd_season_winter/

I wonder if it's a bug or if I'm using the API badly .

**Comment by LetrixZ** [comment]
The API data wasn't updated since Dec 2020. The most up-to-date is this https://animethemes-js.herokuapp.com/ (updates every day) but it doesn't have audio download function yet.

**Comment by LetrixZ** [comment]
I made an update to the 'database' and should be up-to-date. Only new covers and new artists are missing because they take longer to update.
Let me know if I broken anything with it.

EDIT: everything up-to-date
