### ISSUE TITLE
Authors of the songs

### ISSUE THREAD

**Issue by Chortowod** [LetrixZ/animethemes-api#3]
Hello! 
Is there a chance to get song's author with GET /anime/id ? It has 'themes' with title, type, mirrors etc of the song but no author :C

Btw thank you for this great API, i didn't expect that someone done it, great job :3

**Comment by LetrixZ** [comment]
Sadly, r/AnimeThemes only has that info. In the same subreddit there is section for artists that have 5 or more themes in the database (LiSA, Asian Kung-Fu.., etc). I'll add those later at least.

**Comment by LetrixZ** [comment]
Available artist added.

`[{"malId":38000,"title":["Kimetsu no Yaiba","Blade of Demon Destruction","Demon Slayer: Kimetsu no Yaiba"],"cover":"https://cdn.myanimelist.net/images/anime/1286/99889.jpg","season":"Spring 2019","year":2019,"themes":[{"title":"Gurenge","type":"OP V1","mal_id":38000,"theme_id":"38000-00","notes":"","views":0,"mirrors":[{"quality":"default","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-OP1.webm","appUrl":"38000/0/0"},{"quality":"NC, BD, 1080","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-OP1-NCBD1080.webm","appUrl":"38000/0/1"}],"artist":"LiSA"},{"title":"Gurenge","type":"OP V2","mal_id":38000,"theme_id":"38000-01","notes":"","views":0,"mirrors":[{"quality":"default","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-OP1v2.webm","appUrl":"38000/1/0"}],"artist":"LiSA"},{"title":"Gurenge","type":"OP V3","mal_id":38000,"theme_id":"38000-02","notes":"","views":0,"mirrors":[{"quality":"default","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-OP1v3.webm","appUrl":"38000/2/0"}],"artist":"LiSA"},{"title":"Gurenge","type":"OP V4","mal_id":38000,"theme_id":"38000-03","notes":"","views":0,"mirrors":[{"quality":"default","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-OP1v4.webm","appUrl":"38000/3/0"}],"artist":"LiSA"},{"title":"from the edge","type":"ED1","mal_id":38000,"theme_id":"38000-04","notes":"","views":0,"mirrors":[{"quality":"default","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-ED1.webm","appUrl":"38000/4/0"},{"quality":"NC, BD, 1080","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-ED1-NCBD1080.webm","appUrl":"38000/4/1"}],"artist":"LiSA"},{"title":"Kamado Tanjiro no Uta","type":"ED2","mal_id":38000,"theme_id":"38000-05","notes":"Spoiler","views":0,"mirrors":[{"quality":"NC, BD, 1080, Trans","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-ED2.webm","appUrl":"38000/5/0"},{"quality":"NC, BD, 1080, Trans, Lyrics","mirrorUrl":"https://animethemes.moe/video/KimetsuNoYaiba-ED2-Lyrics.webm","appUrl":"38000/5/1"}],"artist":null}]}]`

**Comment by Chortowod** [comment]
That's sad, but thanks at least for that <3
