### ISSUE TITLE
Link to audio file is too complicated.

### ISSUE THREAD

**Issue by ashleney** [LetrixZ/animethemes-api#4]
The API currently returns all data about an anime, and it's video mirrors, however you have to download audio by requesting a link again, instead of getting it by default.

Currently I have to make 2 download functions, one for audio and one for video. This makes it overcomplicated.

I suggest instead of having mirrors lead to a video, it should return an audio alternative too.

**Comment by LetrixZ** [comment]
Actually, for getting the media (video or audio) you need to request:
api/v1/anime/[id]/[theme]/[quality or mirror]/[video/audio]
Could you give me an example of what do you want?
EDIT: do you mean that in the anime details it should have alongside the mirror object a url that leads directly to audio as it does to the video file?

`{
  "malId": 40060,
  "title": [
    "BNA",
    "Brand New Animal"
  ],
  "cover": "https://cdn.myanimelist.net/images/anime/1139/106986.jpg",
  "season": "Spring 2020",
  "year": 2020,
  "themes": [
    {
      "title": "Ready to",
      "type": "OP V1",
      "mal_id": 40060,
      "theme_id": "40060-00",
      "notes": "",
      "views": 4,
      "mirrors": [
        {
          "quality": "default",
          "mirrorUrl": "https://animethemes.moe/video/BrandNewAnimal-OP1.webm",
          "audioUrl": "https://animethemes-api.herokuapp.com/api/v1/anime/40060/0/0/audio",
          "appUrl": "40060/0/0"
        }
      ],
      "artist": null
    },
    {
      "title": "Ready to",
      "type": "OP V2",
      "mal_id": 40060,
      "theme_id": "40060-01",
      "notes": "",
      "views": 0,
      "mirrors": [
        {
          "quality": "default",
          "mirrorUrl": "https://animethemes.moe/video/BrandNewAnimal-OP1v2.webm",
          "audioUrl": "https://animethemes-api.herokuapp.com/api/v1/anime/40060/1/0/audio",
          "appUrl": "40060/1/0"
        }
      ],
      "artist": null
    },...
  ]
}`

**Comment by thesadru** [comment]
Ah no, I mean the actual link given in the response, it would look like this:

```json
​// ID = 40060​
​{​
  ​"malId"​: ​40060​,​
  ​"title"​: ​[​
    ​"BNA"​,​
    ​"Brand New Animal"​
  ​]​,​
  ​"cover"​: ​"https://cdn.myanimelist.net/images/anime/1139/106986.jpg"​,​
  ​"season"​: ​"Spring 2020"​,​
  ​"year"​: ​2020​,​
  ​"themes"​: ​[​
    ​{​
      ​"title"​: ​"Ready to"​,​
      ​"type"​: ​"OP V1"​,​
      ​"mal_id"​: ​40060​,​
      ​"theme_id"​: ​"40060-0"​,​
      ​"notes"​: ​""​,​
      ​"views"​: ​0​,​
      ​"mirrors"​: ​[​
        ​{​
          ​"quality"​: ​"default"​,​
          ​"videoUrl"​: ​"https://animethemes.moe/video/BrandNewAnimal-OP1.webm"​,​
          "audioUrl":"<the audio url here>"
          ​"appUrl"​: ​"40060/0/0"​
        ​}​
      ​]​
    ​}​,​
    ​//...​
  ​]​
​}
```

**Comment by ashleney** [comment]
Yes, having the audio link alongside the video link will simplify a few things and makes it so that there is no need to call for the API again.

**Comment by LetrixZ** [comment]
Done.
