### ISSUE TITLE
Mal and Anilist lead to planned anime too, implement a filter to get only certain statuses.

### ISSUE THREAD

**Issue by ashleney** [LetrixZ/animethemes-api#6]
Right now requesting for user's list leads to anime that hasn't been watched yet, this creates a few problems, I recommend implementing a way to choose only one category.

For example `/mal/letrixZ/completed` instead of `/mal/letrixZ` which should still return every anime

Letting the user choose his own arguments could work too, for example `/mal/letrixZ?status=1`

**Comment by LetrixZ** [comment]
Added

[api/v1/mal/letrix/watching](https://animethemes-api.herokuapp.com/api/v1/mal/letrix/watching):
`[{"mal_id":40956,"title":"Enen no Shouboutai: Ni no Shou","cover":"https://cdn.myanimelist.net/images/anime/1673/107657.jpg","year":2020,"season":"Summer 2020","themes":[{"theme_id":"40956-00","title":"SPARK-AGAIN","type":"OP","notes":"","artist":"Aimer","mirrors":[{"mirror":"https://animethemes.moe/video/EnenNoShouboutaiS2-OP1.webm","quality":[""],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/40956/00/0/audio"}]},{"theme_id":"40956-01","title":"ID","type":"ED","notes":"","artist":null,"mirrors":[{"mirror":"https://animethemes.moe/video/EnenNoShouboutaiS2-ED1.webm","quality":[""],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/40956/01/0/audio"}]}]},{"mal_id":39463,"title":"Gleipnir","cover":"https://cdn.myanimelist.net/images/anime/1380/106565.jpg","year":2020,"season":"Spring 2020","themes":[{"theme_id":"39463-00","title":"Altern-ate-","type":"OP","notes":"NSFW","artist":null,"mirrors":[{"mirror":"https://animethemes.moe/video/Gleipnir-OP1.webm","quality":[""],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/39463/00/0/audio"},{"mirror":"https://animethemes.moe/video/Gleipnir-OP1-NCBD1080.webm","quality":["NC","BD","1080"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/39463/00/1/audio"}]},{"theme_id":"39463-02","title":"Ame to Taieki to Nioi","type":"ED","notes":"NSFW","artist":"Mili","mirrors":[{"mirror":"https://animethemes.moe/video/Gleipnir-ED1.webm","quality":[""],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/39463/02/0/audio"}]}]}]`

[api/v1/anilist/letrix/paused](https://animethemes-api.herokuapp.com/api/v1/anilist/letrix/paused):
`[{"mal_id":38408,"title":"Boku no Hero Academia 4th Season","cover":"https://cdn.myanimelist.net/images/anime/1315/102961.jpg","year":2019,"season":"Fall 2019","themes":[{"theme_id":"38408-00","title":"Polaris","type":"OP1","notes":"","artist":null,"mirrors":[{"mirror":"https://animethemes.moe/video/BokuNoHeroAcademiaS4-OP1.webm","quality":[""],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/38408/00/0/audio"},{"mirror":"https://animethemes.moe/video/BokuNoHeroAcademiaS4-OP1-NCDVD480.webm","quality":["NC","DVD","480"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/38408/00/1/audio"}]},{"theme_id":"38408-02","title":"Star Marker","type":"OP2","notes":"","artist":"KANA-BOON","mirrors":[{"mirror":"https://animethemes.moe/video/BokuNoHeroAcademiaS4-OP2.webm","quality":[""],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/38408/02/0/audio"},{"mirror":"https://animethemes.moe/video/BokuNoHeroAcademiaS4-OP2-NCDVD480.webm","quality":["NC","DVD","480"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/38408/02/1/audio"}]},{"theme_id":"38408-04","title":"Koukai no Uta","type":"ED1","notes":"","artist":null,"mirrors":[{"mirror":"https://animethemes.moe/video/BokuNoHeroAcademiaS4-ED1.webm","quality":[""],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/38408/04/0/audio"},{"mirror":"https://animethemes.moe/video/BokuNoHeroAcademiaS4-ED1-NCDVD480.webm","quality":["NC","DVD","480"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/38408/04/1/audio"}]},{"theme_id":"38408-06","title":"Shout Baby","type":"ED2","notes":"","artist":null,"mirrors":[{"mirror":"https://animethemes.moe/video/BokuNoHeroAcademiaS4-ED2.webm","quality":[""],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/38408/06/0/audio"},{"mirror":"https://animethemes.moe/video/BokuNoHeroAcademiaS4-ED2-NCDVD480.webm","quality":["NC","DVD","480"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/38408/06/1/audio"}]}]},{"mal_id":18679,"title":"Kill la Kill","cover":"https://cdn.myanimelist.net/images/anime/8/75514.jpg","year":2013,"season":"Fall 2013","themes":[{"theme_id":"18679-00","title":"Sirius","type":"OP1","notes":"NSFW","artist":"Eir Aoi","mirrors":[{"mirror":"https://animethemes.moe/video/KillLaKill-OP1.webm","quality":["NC","BD","1080"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/18679/00/0/audio"}]},{"theme_id":"18679-01","title":"ambiguous","type":"OP2","notes":"NSFW, Spoiler","artist":"GARNiDELiA","mirrors":[{"mirror":"https://animethemes.moe/video/KillLaKill-OP2.webm","quality":["NC","BD","1080"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/18679/01/0/audio"}]},{"theme_id":"18679-02","title":"Gomen ne, Iiko ja Irarenai.","type":"ED1","notes":"","artist":null,"mirrors":[{"mirror":"https://animethemes.moe/video/KillLaKill-ED1.webm","quality":["NC","BD","1080"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/18679/02/0/audio"}]},{"theme_id":"18679-03","title":"Shinsekai Koukyougaku","type":"ED2","notes":"","artist":null,"mirrors":[{"mirror":"https://animethemes.moe/video/KillLaKill-ED2.webm","quality":["NC","BD","1080"],"audio":"https://animethemes-api.herokuapp.com/api/v1/anime/18679/03/0/audio"}]}]}]`
